### ISSUE TITLE
Set publisher and subscriber repository as public repositories

### ISSUE THREAD

**Issue by Paullgk** [seapath/ansible#151]
Currently latency tests are using code (publisher and subscriber source code) coming from private repositories. 
The workaround to use them is to build from these source docker images and put them in belonging directory `src/trafgen` and `src/svtools`.
The problem is that latency tests can not be executed by person who does not have access to these sources.
 
The solution would be to set svtools (subscriber source code) and trafgen (publisher source code) repositories as public.

**Comment by eroussy** [comment]
As discussed in last TSC (https://github.com/seapath/TSC/blob/master/TSC_Minutes/20241114_TSC_MOM.md).
These repositories only test pacing (regularity) of Sampled Values reception and not latency itself.
They should be replaced by the new repository https://github.com/seapath/svtrace-ansible.
Related issue on CI repository : https://github.com/seapath/ci/issues/102
