### ISSUE TITLE
rbd list warning 'osd_memory_target' redefined

### ISSUE THREAD

**Issue by dupremathieu** [seapath/ansible#290]
**Describe the bug**
The osd_memory_target in osd section is defined twice, resulting in a warning with the `rbd` command.

**To Reproduce**
Run: `rbd list`

**Expected behavior**
Not warning should be printed.

**Screenshots**
```
rbd list
warning: line 26: 'osd_memory_target' in section 'osd' redefined 
system_vmtest
system_vmtest2
```
/etc/ceph/ceph.conf
```
...
[osd]
osd memory target = 34956902400
osd_max_pg_log_entries = 500
osd_memory_target = 8076326604
osd_min_pg_log_entries = 500
```

**Comment by insatomcat** [comment]
Can you take a look at commit 609704577e46105a1d21bfd50016e7b1a664dfb4 ?
Are you sure you defined osd_memory_target in your inventory without spaces?
Thanks.

**Comment by dupremathieu** [comment]
Ok you right.
