### ISSUE TITLE
ceph error during standalone debian configuration

### ISSUE THREAD

**Issue by dknueppe** [seapath/ansible#437]
**Describe the bug**
Error trying to configure standalone machine with **debian** seapath image.
"ceph auth get-key client.libvirt" fails in the task "Get Ceph libvirt client key"

**To Reproduce**
I've attached my inventory file (as .txt because apperantly github doesn't like attaching .yaml)
changing to the debian-main branch and then copying the file into the inventories,
then executing
cqfd run ansible-playbook -i inventories/welotec_debian_standalone.yaml playbooks/cluster_setup_debian.yaml
reproduces the bug.

**Expected behavior**
No errors druing the basic configuration of my debian machine.
If its an issue with my inventory file, please tell me how to fix it.

**Attachments**
[welotec_debian_standalone.txt](https://github.com/seapath/ansible/files/14667854/welotec_debian_standalone.txt)

**Additional context**
the inventory file is based off of seapath_standalone_definition_example.yml

**Comment by insatomcat** [comment]
Hello,

cluster_setup_debian.yaml is calling cluster_setup_libvirt.yaml, and the objective of cluster_setup_libvirt.yaml is to setup the link between libvirt and ceph (which has no sense on a standalone setup, ceph is not used)
The rest of the playbooks (cluster_setup_ha.yaml and cluster_setup_keys.yaml) also have no sense on a standalone setup (no clustering...).

So basically once you have run cluster_setup_prerequisdebian.yaml and cluster_setup_network.yaml on a standalone setup, you are all set.

**Comment by eroussy** [comment]
Because we have two playbooks, plus one reboot and one check to run, I think it is better to stick with the same global playbook to configure both cluster or standalone machines.
I made a modification on `cluster_setup_debian.yaml` to include that (#445)

**Comment by eroussy** [comment]
Hi @dknueppe
Thanks for you issue.

The playbook `cluster_setup_main.yaml` was indeed not functional for a standalone SEAPATH hypervisor. I corrected that and added documentation about standalone deployment.
Update your debian-main branch with the last changes, your command should work now.
