### ISSUE TITLE
Questioning our use of cgroups

### ISSUE THREAD

**Issue by eroussy** [seapath/ansible#439]
**Context**
There is currently two ways to handle the CPUs on which a VM has access :
- Using the `isolated` VM feature in the inventory : This feature will pin the KVM threads running the VM's vCPUs on the CPUs described in the `cpuset` list.
This feature only pins the KVM threads and not the qemu thread responsible for managing the VM.
- Putting the VM in the `machine-rt` or `machine-nort` slice. These cgroups are configured during Ansible setup. They come with allowed CPUs defined in the variables `cpumachinesrt` and `cpumachinesnort` Ansible variables.
Both KVM and qemu threads of the VM will execute on the allowed CPUs

These two configurations have the same purpose but not the same philosophy. They duplicate a feature and doesn't interact easily with each others.
Plus, the cgroup configuration is only on Debian for now.
We have to clarify the isolation feature we want on SEAPATH.

**Concerns regarding cgroups**
I see two problems with these cgroups today :
- The first is a bug described in the issue #438
- The second is that more threads (for example `qemu-system-x86`) are run on the allowed CPUs of the slice. We may want to run only the KVM threads here.

The second point can cause a problem, for example :
- Give two CPUs to `machine-rt.slice`
- Deploy an RT VM with two CPUs.
In that case, the two RT KVM thread will prevent qemu to execute, and the VM will never boot.
In that case, we have given the slice exactly the number of CPUs we wanted (here : 2) and it will not work.
We should give 3 CPUs to `machine-rt.slice` in order to make it work.

**Isolation of non-RT VMs**
The use of the `machine-nort` cgroup allows isolating threads of non-RT VMs.
Is this relevant to isolate them if we do not have special RT needs. Wouldn't it be better to let the Linux scheduler handle these VMs on the system's CPUs ?

We now need to choose the isolation method we want and use it on both on Debian and Yocto versions.
I leave this question open, feel free to add your remarks below.

**Comment by ebail** [comment]
I think that in any case we need to have a common way to configure RT capabilities to VM.
VM should be deployed on both Debian and Yocto without any change.
@insatomcat @dupremathieu could you please share your opinion ?

Best,

**Comment by dupremathieu** [comment]
I think you have missed the issue @insatomcat.
All processes spawned by libvirt for the virtualization will be in the same cgroup and will share the same cpuset.
Here is an example of processes spawned by libvirtd:
```
qemu-system-x86
qemu-system-x86
log
msgr-worker-0
msgr-worker-1
msgr-worker-2
service
io_context_pool
io_context_pool
ceph_timer
ms_dispatch
ms_local
safe_timer
safe_timer
safe_timer
safe_timer
taskfin_librbd
vhost-16369
IOmon_iothread
CPU0/KVM
kvm
kvm-nx-lpage-recovery-16369
kvm-pit/16369
```

We can pin some processes tweaking the libvirt XML (vcpupin, emulatorpin and iothreadpin) but we can pin it only in the cgroup cpuset and not all processes can be pinned. The unpinned processes are free to run on all CPUs inside the cpuset even pinned CPUs.

It is usually not an issue, but if you have KVM RT task pinned on all available CPUs all other none RT tasks will never be scheduled and the VM will never boot.

So to avoid this in our implementation, we have to reserve an extra CPU core only for these processes.

There are two ways to solve that, remove all cpuset and use isolcpus domaine or keep VM in the machine slice, remove vcpupin in the xml and create a qemu hook to change the slice of KVM thread to machine-rt slice and apply pinning and RT priority.

Regarding the isolcpus deprecated flags, it is just the recommended way which has been changed. I don't know if the kernel preempt RT patch modify something in this part.

@eroussy if you do not want to use cpuset just do not set it inside the Ansible inventory and add the isolcpus domain kernel parameter.

**Comment by insatomcat** [comment]
> All processes spawned by libvirt for the virtualization will be in the same cgroup and will share the same cpuset.

I do not notice this on my setup. Of course I use isolcpus since this is still something done by SEAPATH.
Is your setup running only the slices isolation and no isolcpus?
On our example inventory, cpumachinesrt is the same as isolcpus.

I have a RT VM with 2 vcpu:
```
# virsh dumpxml debian | grep cpu
  <vcpu placement='static'>2</vcpu>
  <cputune>
    <vcpupin vcpu='0' cpuset='2'/>
    <vcpupin vcpu='1' cpuset='14'/>
    <emulatorpin cpuset='4'/>
    <vcpusched vcpus='0' scheduler='fifo' priority='2'/>
    <vcpusched vcpus='1' scheduler='fifo' priority='2'/>
  </cputune>
  <cpu mode='custom' match='exact' check='full'>
  </cpu>
```

And if I ignore the core for "emulation" is what I see on the 2 dedicated cores:
```
# ps -eT -o cmd,pid,tid,rtprio,policy,psr |  grep " 2$"
[cpuhp/2]                        37      37      - TS    2
[idle_inject/2]                  38      38     50 FF    2
[irq_work/2]                     39      39      1 FF    2
[migration/2]                    40      40     99 FF    2
[rcuc/2]                         41      41     10 FF    2
[ktimers/2]                      42      42      1 FF    2
[ksoftirqd/2]                    43      43      - TS    2
[kworker/2:0-events]             44      44      - TS    2
[irq/125-PCIe PME]              325     325     50 FF    2
[kworker/2:1]                   334     334      - TS    2
[irq/151-megasas0-msix3]        488     488     50 FF    2
/usr/bin/qemu-system-x86_64    4739    4775      2 FF    2
root@virtu-elabo3:~# ps -eT -o cmd,pid,tid,rtprio,policy,psr |  grep " 14$"
[cpuhp/14]                      160     160      - TS   14
[idle_inject/14]                161     161     50 FF   14
[irq_work/14]                   162     162      1 FF   14
[migration/14]                  163     163     99 FF   14
[rcuc/14]                       164     164     10 FF   14
[ktimers/14]                    165     165      1 FF   14
[ksoftirqd/14]                  166     166      - TS   14
[kworker/14:0-events]           167     167      - TS   14
[kworker/14:1]                  339     339      - TS   14
[irq/163-megasas0-msix15]       500     500     50 FF   14
[irq/194-eno8403-tx-0]         3226    3226     50 FF   14
/usr/bin/qemu-system-x86_64    4739    4777      2 FF   14
```

Basically nothing besides the vcpu process and bounded kthreads...
So really I don't know what those unpinned libvirt processes are about.

**Comment by eroussy** [comment]
> Basically nothing besides the vcpu process and bounded kthreads...
> So really I don't know what those unpinned libvirt processes are about.

Here you are only looking the processes running exactly on the two cores you choose for the RT VM.
You have to look on all cores in the machine-rt.slice allowed CPU's

For example, on my setup :
The machine-rt slice allowed CPUs are 4-7
```
root@seapath:/home/virtu# cat /etc/systemd/system/machine-rt.slice | grep AllowedCPUs
AllowedCPUs=4-7
```
And the processes on cores 4 to 7 (I display only one part of it) : 
```
root@seapath:/home/virtu# ps -eT -o comm,cmd,pid,tid,rtprio,policy,psr |  grep " [4-7]$"
[...]
qemu-system-x86 /usr/bin/qemu-system-x86_64  158603  158603      - TS    4
call_rcu        /usr/bin/qemu-system-x86_64  158603  158607      - TS    4
log             /usr/bin/qemu-system-x86_64  158603  158608      - TS    4
msgr-worker-0   /usr/bin/qemu-system-x86_64  158603  158609      - TS    4
msgr-worker-1   /usr/bin/qemu-system-x86_64  158603  158610      - TS    4
msgr-worker-2   /usr/bin/qemu-system-x86_64  158603  158611      - TS    4
service         /usr/bin/qemu-system-x86_64  158603  158615      - TS    4
io_context_pool /usr/bin/qemu-system-x86_64  158603  158616      - TS    4
io_context_pool /usr/bin/qemu-system-x86_64  158603  158617      - TS    4
ceph_timer      /usr/bin/qemu-system-x86_64  158603  158618      - TS    4
ms_dispatch     /usr/bin/qemu-system-x86_64  158603  158619      - TS    4
ms_local        /usr/bin/qemu-system-x86_64  158603  158620      - TS    4
safe_timer      /usr/bin/qemu-system-x86_64  158603  158621      - TS    4
safe_timer      /usr/bin/qemu-system-x86_64  158603  158622      - TS    4
safe_timer      /usr/bin/qemu-system-x86_64  158603  158623      - TS    4
safe_timer      /usr/bin/qemu-system-x86_64  158603  158624      - TS    4
taskfin_librbd  /usr/bin/qemu-system-x86_64  158603  158625      - TS    4
vhost-158603    /usr/bin/qemu-system-x86_64  158603  158648      - TS    4
vhost-158603    /usr/bin/qemu-system-x86_64  158603  158649      - TS    4
IO mon_iothread /usr/bin/qemu-system-x86_64  158603  158650      - TS    4
CPU 0/KVM       /usr/bin/qemu-system-x86_64  158603  158651      1 FF    5
CPU 1/KVM       /usr/bin/qemu-system-x86_64  158603  158652      1 FF    6
kvm             [kvm]                        158626  158626      - TS    4
kvm-nx-lpage-re [kvm-nx-lpage-recovery-1586  158627  158627      - TS    4
kvm-pit/158603  [kvm-pit/158603]             158654  158654      - TS    4
kworker/4:0-kdm [kworker/4:0-kdmflush/254:0 2099770 2099770      - TS    4
```
The question is : 
should all these threads run on these CPUs ?
And if yes, how can we run them on other CPUs than the 4th ?

**Comment by dupremathieu** [comment]
@insatomcat you didn't notice because we have a large cpuset range.

Reduce your machine-rt cpuset to have a number of CPUs cores equals to the number of your virtual CPUs.

**Comment by dupremathieu** [comment]
What we want for emulatorpin is to use the no-rt cpuset (0-1,7-13,19-N in your case) to avoid reserve and loose a core for it.

**Comment by dupremathieu** [comment]
It should be possible using qemu hook, but to me, we should just mention it in the documentation.

I suggest indicating in the documentation:
* The pinned processes have to be pinned inside the cgroup cpuset.
* If you use RT privilege KVM threads, the minimal cpuset size has to be: total of number of vcpus + 1.
* If it is not what you want, do not define any cgroup cpuset and use isolcpus domain instead.

**Comment by insatomcat** [comment]
> If you use RT privilege KVM threads, the minimal cpuset size has to be: total of number of vcpus + 1

--> total of number of "_isolated_" vcpus + 1

You don't have to isolate all the vcpu. You may even need a "non isolated" vcpu for the housekeeping inside the vm.
So basically if you need N isolated cores for your realtime workload, your guest may need N+1 cores.
But this "+1" can be shared with other RT guests and with the emulator.

**Comment by eroussy** [comment]
> I suggest indicating in the documentation:
>     * The pinned processes have to be pinned inside the cgroup cpuset.
>     * If you use RT privilege KVM threads, the minimal cpuset size has to be: total of number of vcpus + 1.
>     * If it is not what you want, do not define any cgroup cpuset and use isolcpus domain instead.

I don't think it is a good idea to propose both.
We should choose one isolation method and argument why we choosed it.

Personally,
- I don't like that the `emulatorpin` cpuset has to be in the `machine-rt.slice` allowed CPUs. We cannot pin him where we want.
- I don't like that we have to assigned `number_of_isolated_vcpu + 1` cores to the slice. I find this confusing. It also needs one more core which is difficult on machines with few cores.
- I also don't like that we have to choose the allowed CPUs during ansible setup. I think these have to be chosen for each VMs during the deployment.
- Finally, I think that all the emulator CPUs have to be handled by Linux scheduler on system's core.
  - It takes less cores
  - It will be well scheduled by Linux
  - The user don't have to think about them
  - It is less difficult to use
  - It avoid race conditions (#438)

The only argument I see (for now) in favor of using cgroups is that it prevents from hardware processor attacks like meltdown and spectre. 
Do we really want to prevent these types of attacks ?
Is there any other argument I'm missing ?

**Comment by eroussy** [comment]
Hi all,

We need to close this question.
I discussed with Mathieu and we conclude that :
- Cgroup are useful for specific configurations
- Cgroup must remain optional
- Cgroup are an advanced feature of SEAPATH and must not be presented directly to newcomers.
- The isolcpu question will soon be handled with tuned, which is better.

So, regarding the work to do :
- All the systemd slices (system, user, ovs, machine, machine-rt and machine-nonrt) are already optionnal and must stay optionnal.
- Their configuration must be backported to yocto (and also be optional)
- Tuned will be merged to handle isolcpu
- Documentation should be written about the technical questions we discussed in this issue (emulatorpin, qemu thread, `number_of_isolated_vcpu + 1` etc ...)
- Slices variable (`cpusystem`, `cpuuser` ...) must be removed of the inventory examples and described in the inventories README as advanced feature.

@insatomcat @dupremathieu what do you think of that ? Did I miss something ?

**Comment by insatomcat** [comment]
I'm ok with all that.

**Comment by ebail** [comment]
Great. Maybe @eroussy it worth documenting it on LFEnergy Wiki ?

**Comment by eroussy** [comment]
The topic is now covered in this wiki page : https://wiki.lfenergy.org/display/SEAP/Scheduling+and+priorization
Feel free to reopen if you have questions or remarks.
