### ISSUE TITLE
VM`s console access is disabled after setup_debian playbook

### ISSUE THREAD

**Issue by eroussy** [seapath/ansible#463]
**Describe the bug**
A virtual machine deployed on an hypervisor is accessible with `virsh console vm`.
This is not possible anymore after the debian playbook is applied on the VM.
In fact, the service `getty@ttyS0` is disabled on the VM.

**To Reproduce**
1. Set up a SEAPATH Debian hypervisor (standalone or cluster)
2. Create a debian VM with https://github.com/seapath/build_debian_iso
3. Deploy the VM on the hypervisor
4. SSH on the hypervisor and do `virsh console vm`. It works
5. Apply the playbook `cluster_setup_debian.yaml` on the VM
6. Reboot the VM
7. SSH on the hypervisor and do `virsh console vm`. It doesn't work anymore.
8. SSH on the VM and type `systemctl status getty@ttys0`. The service is disabled.

**Expected behavior**
The VM should be accessible with the console at any time.

**Comment by insatomcat** [comment]
This is what the grub_append option is designed for. The example in the inventory is what you're asking for.

https://github.com/seapath/ansible/blob/fa426a3bfb25890157165046a6d7f2a784de9b71/inventories/seapath_cluster_definition_example.yml#L273

**Comment by eroussy** [comment]
Oh thanks, my bad.
I'm gonna add that to the VM inventory
