### ISSUE TITLE
Deprecated and unaligned ceph versions

### ISSUE THREAD

**Issue by eroussy** [seapath/ansible#491]
The Debian and Yocto versions of SEAPATH uses different versions of ceph, and they are both outdated.

SEAPATH Yocto is on the Kirkstone release, which is packaged with Ceph Octopus (15.2.15)
This version has been outdated since September 2022.
The new official Yocto LTS is Scarthgap and package the last Ceph version. The problem will be resolved when porting meta-seapath to Scarthgap

SEAPATH Debian is on the Bookworm stable release, which packaged the Pacific version of Ceph (16.2.11)
This version has been outdated since april 2024 (https://docs.ceph.com/en/latest/releases/)
There is currently no solution to update ceph. The new version of Debian uses the last version of ceph, but has no release date for now.
I emailed the Ceph packaging team of Debian on this subject. I will keep you informed.

In addition, it would be better to align the versions of ceph on Debian and Yocto.
It is always better to have the same version for compatibility, and it will allow us to use the same version of ceph-ansible and thus the same version of Ansible.
This is a very important point to realign the `main` and `debian-main` branches.

**Comment by dupremathieu** [comment]
Ceph version are aligned to the Ceph Pacific (16) version.

**Comment by eroussy** [comment]
This is done by https://github.com/seapath/meta-seapath/pull/251 and #621
