### ISSUE TITLE
debiancentos: add_livemigration_user: don't add the ssh key for admin_user

### ISSUE THREAD

**Issue by Revalioli** [seapath/ansible#640]
`admin_user` was up until now only used with the debian branch and didn't exist on the Yocto (main) branch.

On the debiancentos branch, the `add_livemigration_user` role sets the ssh key for the `livemigration_user` but also for the `admin_user`.
- It is not necessary to copy the key for `admin_user` as only `livemigration_user` performs live migrations.
- Inventories for Yocto Seapath don't define this user, so it complicated compatibility with the branch merge.

Removing this key copy for `admin_user` would improve compatibility with existing Yocto Seapath

**Comment by dupremathieu** [comment]
To me, the admin_user setup should be set outside the add_livemigration_user role.

**Comment by eroussy** [comment]
Corrected by #643
