### ISSUE TITLE
Allow to remove cluster

### ISSUE THREAD

**Issue by ebail** [seapath/ansible#97]
Check and document how to remove clustering features with Seapath-Debian.

**Comment by insatomcat** [comment]
Unless I'm missing something, Seapath without clustering is basically "just" using libvirt on a single deployed node.
Basically you need to:
- deploy one node with build_debian_iso
- setup basic networking (with networkd preferably)
- use virsh to manage a vm (disk is qcow2 file)

**Comment by eroussy** [comment]
Closing this PR as done.
To deploy SEAPATH Debian on one machine only (without clustering feature), the `standalone_machine` field must be used in the inventory.
One example is given here : https://github.com/seapath/ansible/blob/debian-main/inventories/seapath_standalone_definition_example.yml
